### ISSUE TITLE
RecyclerView inside a ScrollView gets heightSpec of 0

### ISSUE THREAD

**Issue by DeanSingh** [serso/android-linear-layout-manager#1]
If RecyclerView gets put into a ScrollView, then during measure step its height is unspecified (because ScrollView allows any height) and gets equal to minimum height (as per implementation) which is apparently zero.

Any ideas on how we can still get wrap_content work be enforced there?

**Comment by serso** [comment]
Generally it's not a good idea to put one scrollable view into another. What are you trying to achieve? RecyclerView supports scrolling out-of-the-box, you don't need to wrap it with ScrollView. For more details please refer to stackoverflow [answer](http://stackoverflow.com/questions/3495890/how-can-i-put-a-listview-into-a-scrollview-without-it-collapsing).

**Comment by serso** [comment]
Please reopen the issue with more details

**Comment by dimsuz** [comment]
There's a perfectly valid scenario: when I use RecyclerView with a HORIZONTAL layout inside a ScrollView. And this library's layout manager seems to fail to handle this case, which would be great if it worked...
