### ISSUE TITLE
SmoothScrolling issue

### ISSUE THREAD

**Issue by hrskrs** [serso/android-linear-layout-manager#14]
If there are multiple items, it wont scroll smoothly (in `Fragment`)...

**Comment by MohamadAtieh** [comment]
What about Activity scroll? I can confirm that since I tried a similar implementation and the scrolling stopped being smooth.

**Comment by yesimroy** [comment]
get the same issue, when more than two recyclerView put together, my phone (ASUS PadFone S, Android 5.0) can't scroll very smooth. But the device (belows 5.0) can scroll very smooth.

**Comment by hrskrs** [comment]
Yeah same issue. It is not scrolling smoothly only on 5.0 devices

**Comment by rajkshah14** [comment]
Found any solution to this?

**Comment by serso** [comment]
I can't reproduce the issue. Scrolling in the sample app works fine. Please provide a source code which doesn't work

**Comment by ogungulec** [comment]
This behaviour happens when using RecyclerView inside another scrollable view like ScrollView. However, it's not a bug and caused by LinearLayoutManager. 

Solution: Disable nested scrolling on RecyclerView using    recyclerView.setNestedScrollingEnabled(false);

**Comment by xudshen** [comment]
@ogungulec works for me, thx
