### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by malacavilla** [serso/android-linear-layout-manager#15]
Without a license, this project isn't open source and no one can use the code.

Please use something like http://choosealicense.com/ to decide what license to use.

**Comment by PaeP3nguin** [comment]
Loving the library so far, it's the only one that works for me! But as the previous commenter asked, we would really appreciate if you would add a license so that we can use it legally.

**Comment by nextmunich** [comment]
+1 on a license file - would be a big help so that you let people know about how you intend the source to be used.
