### ISSUE TITLE
unable to set wrap_content as horizontal recyclerview when setting wrap_content its displaying nothing 

### ISSUE THREAD

**Issue by erumhannan** [serso/android-linear-layout-manager#18]

**Comment by stasbar** [comment]
The same to me :-1:

**Comment by onooma** [comment]
Same problem here, Any one have a solution?

**Comment by IlyaEremin** [comment]
+1

**Comment by serso** [comment]
Have you tried sample app? Does it work there?

**Comment by silviahisham** [comment]
same problem happens to me

**Comment by serso** [comment]
I can't reproduce the issue. Please provide source code where wrap_content doesn't work.
