### ISSUE TITLE
RecyclerView.onBindViewHolder invoked multiple times

### ISSUE THREAD

**Issue by smujaddid** [serso/android-linear-layout-manager#20]
The method RecyclerView.onBindViewHolder invoked multiple times for the same position. This is a real problem for my navigation drawer in my project. If I use the standard LinearLayoutManager, this problem is not happening.

My logs
10-08 18:28:56.293 6524-6524/id.co.xxx D/BIND_VIEW_HOLDER: Bind Selected Position : 3
10-08 18:28:56.303 6524-6524/id.co.xxx D/BIND_VIEW_HOLDER: Bind Selected Position : 3
10-08 18:28:56.323 6524-6524/id.co.xxx D/BIND_VIEW_HOLDER: Bind Selected Position : 3

**Comment by serso** [comment]
Yes, this might happen and there is nothing I can do.
