### ISSUE TITLE
Last divider decoration is not drawn

### ISSUE THREAD

**Issue by CodeJjang** [serso/android-linear-layout-manager#23]
Using this layout manager, everything works fine except that the last item divider decoration is not drawn on screen.
But, when using the default LinearLayoutManager, it is drawn (as expected).

Also tried using your custom divider decoration class, but it still doesn't work.

Layout:

    <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:paddingLeft="28dp"
	android:paddingRight="28dp" 
	android:layout_marginBottom="8dp"
	android:layout_marginTop="8dp">
    
    
    <ImageView
		    android:id="@+id/icon"
		    android:layout_width="30dp"
		    android:layout_height="30dp"
		    android:layout_alignParentLeft="true"
		    android:background="@drawable/ic_group_members"/>
    
    <TextView
		    android:id="@+id/text"
		    android:layout_width="wrap_content"
		    android:layout_height="wrap_content"
		    android:layout_alignBottom="@+id/icon"
		    android:layout_centerVertical="true"
		    android:layout_marginLeft="15dp"
		    android:layout_toRightOf="@+id/icon"
		    android:textSize="18sp"
		    android:textStyle="bold"
		    android:text="@string/members_title"/>
	

	<android.support.v7.widget.RecyclerView    
	    android:id="@+id/recycler_view"
	    android:paddingTop="2dp"
	    android:layout_below="@id/text"
	    android:layout_width="match_parent"
	    android:layout_height="match_parent"
	    app:layout_behavior="@string/appbar_scrolling_view_behavior"/> 
	    
    </RelativeLayout>

**Comment by serso** [comment]
org.solovyev.android.views.llm.DividerItemDecoration first and last dividers are disabled by default. You can enable them using special constructor.

**Comment by CodeJjang** [comment]
By first divider you mean the divider BEFORE first item? I guess so.
And the last divider is obviously the divider after the last item...
Well, in the default imlementation of the linear layout manager, the last divider is drawn, so I wonder why you chose not to...

In the bottom line, HOW do I enable the last one please? I tried playing with the c'tor without luck.

**Comment by serso** [comment]
"first" means a divider before the first element, "last" - is after the last element. Use constructorn of DividerItemDecoration with last=true. Dividers before and after the list are disabled because they divide nothing.
