### ISSUE TITLE
Not calculating height

### ISSUE THREAD

**Issue by mohammedhammouri** [serso/android-linear-layout-manager#29]
I have a recyclerView with custom views inside it and inside the cutsom view I have another recyclerView ........ I don't think if this info will help you.

My problem is with the first(main) recyclerview , i think!! ... when I have one child inside it it doesn't recalculate it size when the height of the custom view changes, but when I have more than one child it recalculate the size when the height of the custom view change.

**Comment by sevar83** [comment]
In my case I have one `RecyclerView` with sections and thus it has varying number of items. Calling `mRecyclerView.requestLayout()` after adapter change makes it work... hopefully.
