### ISSUE TITLE
It does not work for horizontal orientation list.

### ISSUE THREAD

**Issue by gaurav-mishra8** [serso/android-linear-layout-manager#31]
My recycler view is 

> <android.support.v7.widget.RecyclerView
>                 android:id="@+id/rv_friend_list"
>                 android:layout_width="match_parent"
>                 android:layout_height="wrap_content"
>                 android:minHeight="@dimen/ad_detail_friend_recycle_min_height" />

LinearLayoutManager layoutManager = new WrapLinearLayoutManager(getActivity(),
                LinearLayoutManager.HORIZONTAL, false); 
I am setting horizontal orientation for list as I want width to wrap content but it does not work.

**Comment by grennis** [comment]
Google now supports WRAP_CONTENT size natively in the recycler view, so no need for workarounds anymore. http://android-developers.blogspot.com.br/2016/02/android-support-library-232.html
