### ISSUE TITLE
Android Support Library 23.2 now supports WRAP_CONTENT in RecyclerView

### ISSUE THREAD

**Issue by bryant1410** [serso/android-linear-layout-manager#32]
http://android-developers.blogspot.com.uy/2016/02/android-support-library-232.html

**Comment by sibeliusseraphini** [comment]
@bryant1410 could u provide an example of how to use WRAP_CONTENT to solve the same problem that this repo solves?

**Comment by bryant1410** [comment]
Yes. It's used here in this layout: https://github.com/xmartlabs/Android-Base-Project/blob/demo/app/src/main/res/layout/activity_main.xml#L61 and in this activity: https://github.com/xmartlabs/Android-Base-Project/blob/demo/app/src/main/java/com/xmartlabs/template/ui/MainActivity.java#L66

**Comment by sibeliusseraphini** [comment]
thanks
